project:
  type: book
  output-dir: docs

book:
  title: "SOC 300: Introduction to R"
  author: "Daulton Selke"
  date: "9/5/2025"
  sidebar:
    search: true
    title: " "
    logo: cover.jpg

  chapters:
    - index.qmd
    - part: "Day 1: R Fundamentals"
      chapters: 
        - objects_and_operations.qmd
        - vectors_and_data.qmd
        - data_frames.qmd
        - factors.qmd
    - part: "Day 2: Survey Data and Univariate Analysis"
    - part: "Day 3: Bivariate Analysis with the GSS"


bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

