project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R for Quantitative Social Science Research"
  subtitle: "SOC 300: Social Research Methods"
  author: "Daulton Selke"
  date: "9/3/2025"
  sidebar:
    search: true
    title: " "
    logo: cover.jpg

  chapters:
    - index.qmd
    - background.qmd
    - part: "Day 1: Getting Started"
      chapters: 
        - getting_started.qmd
        - packages_and_tidy.qmd
    - part: "Day 2: Survey Data and Univariate Analysis"
      chapters: 
        - recoding_variables.qmd
        - univariate_categorical.qmd
        - univariate_numeric.qmd
    - part: "Day 3: Bivariate Analysis with the GSS"
      chapters:
        - bivariate_categorical.qmd
    - part: "Day 4: Multivariable Analysis and Elaboration"
    - part: "Day 5: Making Better Visualizations"
      chapters:
        - viz_introduction.qmd
        - data_viz.qmd


bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

