project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R"
  subtitle: "SOC 300: Social Research Methods"
  author: "Daulton Selke"
  date: "9/3/2025"
  sidebar:
    search: true
    title: " "
    logo: cover.jpg

  chapters:
    - index.qmd
    - part: "Day 1: Getting Started"
      chapters: 
        - background.qmd
        - getting_started.qmd
        - packages_and_tidy.qmd
        - usajobs_embeddings.qmd
    - part: "Day 2: Survey Data and Univariate Analysis"
    - part: "Day 3: Bivariate Analysis with the GSS"
    - part: "Day 4: Multivariable Analysis and Elaboration"
    - part: "Day 5: Data Visualization and ggplot"
      chapters:
        - viz_introduction.qmd


bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

