{
  "hash": "77241cd7c9c79652cdee7867bfb985c8",
  "result": {
    "engine": "knitr",
    "markdown": "# Univariate: Categorical\n\nBefore we start examining the relationships between multiple variables, we have to look under the hood of our variables individually and make sure we have a good sense of what they are like. \n\nWe want to know the frequency distribution of the response values, the measures of central tendency, and the dispersion. In other words, we want to see how many respondents chose each response value, which response values are most typical for each variable, and the extent to which the response values vary. \n\nLuckily for us, R has plenty of tools for generating these quantitative summaries, as well as visualizing them in the form of barplots, histograms, and other common styles for displaying data.\n\nThis tutorial will cover each of these elements, and I will highlight any differences specific to certain levels of measurement along the way.\n\n## Frequency Distributions\nLet's start with categorical variables. We will start with frequency distributions by way of frequency tables and bar plots. Then, we will talk about measures of tendency and observe when they are appropriate for categorical data. \n\n### Frequency tables\n\nFrequency tables are the most effective way to report the frequency distributions for categorical variables. There are actually a ton of different ways to produce this kind of table in R, but we are going to use some convenient functions from the `janitor` package, so let's go ahead and load that in. \n\nIf you are on a lab computer, try to load it with `library()` first. If you get an error, go ahead and install it with `install.packages()` and then load it in.\n\nWhile we're at it, we'll also bring in `tidyverse` and load in our GSS subset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\nlibrary(tidyverse)\nload(\"our_gss.rda\")\n```\n:::\n\n\nLet's go ahead and work with one of our `partyid` recodes from last time. We'll use `partyid_recoded`, where we retained all the party choices but collapsed the categories of degree (e.g. strong democrat + not very strong democrat = Democrat). \n\n\n::: {.cell}\n\n:::\n\n\nWe can use a simple command with `tabyl()` from the `janitor` package to produce our frequency tables. Let's take a look at some output, and I'll go through a couple details and mention some further specifications we can make.\n\nAll we need to do is give our data frame as the first argument, and then our particular variable column as the second argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Without pipe operator\ntabyl(our_gss, partyid_recoded)\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# With pipe operator\nour_gss |>\n  tabyl(partyid_recoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n partyid_recoded    n     percent valid_percent\n        Democrat 1046 0.295146727    0.29809062\n     Independent 1565 0.441591422    0.44599601\n      Republican  792 0.223476298    0.22570533\n     Other Party  106 0.029909707    0.03020804\n            <NA>   35 0.009875847            NA\n```\n\n\n:::\n:::\n\n\nNow, we have a frequency table for `partyid_recoded`!\n\nEach row is a level of `partyid_recoded`. The `n` column refers to the sample size, so, for example, 1,565 respondents indicated that they were Independents. \n\nWe then have two different columns for percentages. The `percent` column is the proportion of all respondents that chose each response value---while including NA values. Often, we want to get a proportion for only the sample of those who actually answered the question. This is what the `valid_percent` column indicates and is what we are often looking for. \n\nLet's break it down a little for clarity. \n\nThe total number of respondents is the sum of the 'n' column. \n\n1565 + 1046 + 792 + 106 + 35 = 3,544 \n\nNote that this is also the number of observations in our data frame\n\nThere are also 35 observations coded as NA, so the total number of *valid* respondents is 3,509.\n\nNow, I'll give the calculations for the `Independent` row.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# I'm going to define a few objects here for simplicity.\n\nall_respondents <- 3544\n\nall_minus_na <- (3544 - 35)\n\nindependents <- 1565\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Percent column\n\nindependents / all_respondents\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4415914\n```\n\n\n:::\n\n```{.r .cell-code}\n# Valid percent column\n\nindependents / all_minus_na\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.445996\n```\n\n\n:::\n:::\n\n\nIn this case, there really aren't that many NA values, so it does not change too much. In general, we will often discard NA categories in analyses we do for the course, but they give us important information about the survey and can be useful for some questions, so it's important to keep track of them nonetheless. \n\nNow, let's clean a couple things up with the `adorn_()` functions.\n\nLet's add a row for totals, turn the proportions into percentages, and round the decimals. We can use the pipe operator to quickly leverage a few different `adorn_()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss |>\n  tabyl(partyid_recoded) |>\n  adorn_totals(where = \"row\") |>\n  adorn_pct_formatting() |>\n  adorn_rounding(digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n partyid_recoded    n percent valid_percent\n        Democrat 1046   29.5%         29.8%\n     Independent 1565   44.2%         44.6%\n      Republican  792   22.3%         22.6%\n     Other Party  106    3.0%          3.0%\n            <NA>   35    1.0%             -\n           Total 3544  100.0%        100.0%\n```\n\n\n:::\n:::\n\nWe don't need to supply any input for `adorn_pct_formatting()`---which changes the proportions to percentages---but a couple of these functions do require inputs.\n\nFor `adorn_totals()`, we give \"row\" for the `where` input, which tells the function that we want the totals column to appear as a row.\n\nFor `adorn_rounding()`, we give an input for `digits`, which is the number of digits we want after the decimal point. We'll keep 2 and thereby round to the hundredth. \n\nLastly, if we want, we can also make the column names a little nicer. It may not be obvious because we've just been displaying this table rather than storing it as an object, but it's actually a data frame, so we can edit the column names directly.\n\nLet's save it as an object so that's easier to see.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_table <- our_gss |>\n  tabyl(partyid_recoded) |>\n  adorn_totals(where = \"row\", na.rm = TRUE) |>\n  adorn_pct_formatting() |>\n  adorn_rounding(digits = 2)\n```\n:::\n\n\nWe can then use the `colnames()` function. Let's supply our table data frame as an input to get a feel for it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(our_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"partyid_recoded\" \"n\"               \"percent\"         \"valid_percent\"  \n```\n\n\n:::\n:::\n\nIt lists out the character vector of the 4 column names, and we can actually just write over them by supplying our desired column names as a character vector. If we assign that character vector to `colnames(our_table)`, it will overwrite the column names. Make sure the labels are in the same order as they appear in the data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(our_table) <- c(\n  \"Political Party\",\n  \"Frequency\",\n  \"Percent\",\n  \"Valid Percent\"\n  )\n\nour_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Political Party Frequency Percent Valid Percent\n        Democrat      1046   29.5%         29.8%\n     Independent      1565   44.2%         44.6%\n      Republican       792   22.3%         22.6%\n     Other Party       106    3.0%          3.0%\n            <NA>        35    1.0%             -\n           Total      3544  100.0%        100.0%\n```\n\n\n:::\n:::\n\nExcellent! We'll learn how to make this even nicer a bit later in the semester, but this looks pretty good for now.\n\nLet's look at one last visualization technique for categorical variables.\n\n### Bar plots\n\nFor categorical data, bar plots are often the way to go. These typically have the response values on the x axis, and the count or percentage of each response value is tracked on the Y axis. \n\nMuch like with tables, we'll learn some fancier ways to do this later in the semester. But, in the meanwhile, base R has some great plotting functions that can be used very easily without much specification. They're not the prettiest out of the box, but they will do everything we need.\n\nFor `barplot()`, we just need the variable column that we are trying to plot. But, there's one thing to remember when you are trying to get a barplot this way---you have to provide the result of `summary(my_variable)` rather than the variable column directly. \n\nI'll show you a couple ways to do that, which all do the exact same thing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# No pipe operator; summary() nested inside barplot()\n\nbarplot(summary(our_gss$partyid_recoded))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# With pipe operator\nour_gss$partyid_recoded |>\n  summary() |>\n  barplot()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make separate object for the summary() output\n\nmy_summary <- summary(our_gss$partyid_recoded)\n\nbarplot(my_summary)\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nNow, as I mentioned, we won't spend too much time adjusting these plots for now, but there are a couple things we can do to make this a little better to look at for now.\n\nFor one, our response labels (Democrat, Republican, Independent, etc) Actually look pretty good in the display here, but it's not uncommon for these to get cut off if we have several response categories or the response names are especially long. So, I'll show you how to reduce the font size as one potential fix for that. \n\nWe can add the `cex.names` argument to `barplot()`. This argument takes a number, and the number should reflect an intended ratio of the default font size for our value labels on the x-axis. So, for example, I would enter '2' if I wanted the font to be twice as big. For our purposes, I want to reduce the font a bit, so we'll enter '.75' to reduce the font size by 1/4. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss$partyid_recoded |>\n  summary() |>\n  barplot(cex.names = .75)\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nWe can also add some simple descriptive information for the plot, such as a title and labels for the x and y axis. We can do so within `barplot()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss$partyid_recoded |>\n  summary() |>\n  barplot(\n    cex.names = .75, \n    main = \"Count of GSS Respondents by Political Party\",\n    xlab = \"Political Party\",\n    ylab = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nAs a final point, I'll also note that you can pass `partyid_recoded` into the function `na.omit()` before `summary()` if you ever want to produce a barplot that excludes NA responses. `na.omit()` will remove any NA values from the vector we provide it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss$partyid_recoded |>\n  na.omit() |>\n  summary() |>\n  barplot(\n    cex.names = .75,\n    main = \"Count of GSS Respondents by Political Party\",\n    xlab = \"Political party\"\n  )\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n## Measures of Central Tendency\nNow, let's talk about measures of central tendency. Because there is no mathematically meaningful relationship between the different levels of a categorical variable, our options for reporting measures of central tendency are a little more limited.\n\nThe classic central tendency measures are the mode, the median, and the mean. For categorical variables, it is not ever meaningful to take the mean. As we saw back on our first day with R, you will get a warning message if you try to run `mean()` on a character or factor variable. \n\nOur options are limited to the mode or the median, depending on the distribution of responses.\n\n### Nominal variables\nIn the case nominal variables, there is no semblance of meaningful arrangement to the categories. In this case, we can only report the mode. \n\nOften times, we can just glean this from the frequency tables, or even just the `summary()` output. Let's stick with `partyid_recoded` as an example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(our_gss$partyid_recoded)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Democrat Independent  Republican Other Party        NA's \n       1046        1565         792         106          35 \n```\n\n\n:::\n:::\n\n\nRemember that the mode is just the value with the most occurrences. So, the mode here is 'Independent'. \n\nThis is likely sufficient for the variables we will work with, but you may also want a method that's a little more exacting and does not depend on visually scanning for the mode. \n\nR does not actually have a built-in `mode()` function like it does for `mean()` and `median()`. Well, it does have `mode()`, but it evaluates the 'mode' of the data, which, in this case, is actually the 'storage mode', or the data type. This is not particularly helpful for us, but we can use another convenient package called `DescTools`.\n\nIf you are on a lab computer, go ahead and try loading it with `library()` first. If it does not load, then install it with `install.packages(\"DescTools\")` and then load it in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\n```\n:::\n\n\nThen, we can just use the `Mode()` function within DescTools. Make sure you capitalize the 'M', as this is what distinguishes the DescTools function from the base R function.\n\nAlso, be sure to include `na.rm = TRUE`, as R will not know what to do with the NA values when calculating the mode, so we need to tell it to disregard them.\n\n::: {.cell}\n\n```{.r .cell-code}\nMode(our_gss$partyid_recoded, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Independent\nattr(,\"freq\")\n[1] 1565\nLevels: Democrat Independent Republican Other Party\n```\n\n\n:::\n:::\n\n\nSo, this also gives us our mode, and is a bit more precise a way of doing so---especially when we have a bunch of possible response values.\n\nNote that it also tells us how many responses were associated with that value (1565).\n\nNow, let's talk about ordinal variables, where we have another consideration.\n\n### Ordinal variables\n\nWhile ordinal variables are still categorical and thus unamenable to mathematical analysis, they do have a meaningful order. This means that it's possible for us to take the median value of an ordinal variable.\n\nHowever, we can only do so when the variable is normally distributed. If there is significant skew in the distribution of responses, then we will need to report the mode for an ordinal variable.\n\nLet's refresh our memory on distributions before we take some central tendency measures of ordinal variables in the GSS. \n\n##### Distribution assumptions\nIf the responses of an ordinal variable are normally distributed, we can take the median. \n\nIn the ideal form of the normal distribution, you have a mean of 0 and a standard deviation of 1, where roughly 68% of values are within 1 standard deviation in either direction of the mean, and roughly 95% of values are within 2 standard deviations in either direction.\n\nHowever, in practice, our distributions are unlikely to reflect the ideal normal distribution. But, if they are roughly normal, we can work with that.\n\nI'll display a few distributions here as a reminder, starting with the classic normal distribution. If you produce a barplot and find the data looks generally like this---where the majority of variables are concentrated around the middle of the distribution---then you can report the median response rather than the mode.\n\n\nHere's the normal distribution\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nHere's a left-skewed distribution. This is when there's a prominent 'tail' on most of the left-hand side of the distribution. In other words, when most of the values are concentrated on the right-hand side of the distribution (the upper end), then we have a left-skew.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nLastly, here's a right-skewed distribution. As you can probably guess from the description of a left-skewed distribution, a right-skew occurs when we have a long tail through most of the right-hand side of the distribution. In other words, most values are concentrated on the left-hand side. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nSo, if the distribution of your variable looks (mostly) like the normal distribution, go ahead and take the median of any ordinal variable.\n\nLet's go ahead and practice doing that with the `age_ord` variable we created last time.\n\n\n::: {.cell}\n\n:::\n\n\nFirst, we'll verify that the distribution allows for reporting the median.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss$age_ord |>\n  na.omit() |>\n  summary() |>\n  barplot(\n    main = \"Age Distribution of GSS Respondents\",\n    xlab = \"Age grouping\"\n  )\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nWell, hold on now. In the case of `age_ord`, it looks like we'd actually want to take the mode, because it's a bit left-skewed. \n\nLet's try the `happy` variable. This is an ordinal variable in our subset that we haven't used yet. We'll see if its normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n our_gss$happy |>\n  na.omit() |>\n  summary() |>\n  barplot(\n    main = \"Happiness Distribution of 2022 GSS Respondents\",\n    xlab = \"Response value\"\n  )\n```\n\n::: {.cell-output-display}\n![](univariate_categorical_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\nPerfect. The distribution is exactly what we want to see. Most of the variables are concentrated at the midpoint of the distribution, with tails on either side. So, as it's roughly normally distributed, `happy` will serve as a good example of a case where taking the median of an ordinal variable is appropriate.\n\nNow, the median response value is fairly apparent in this case, but I'll show you a method that you can use to calculate the median of any ordinal variable you might come across.\n\nWhile R has a built-in `median()` function, it actually only works with numeric data. Fear not, however, as we can also use the `DescTools` again. \n\nIn order to distinguish itself from the default `median()` function, the DescTools package uses a capitalized 'M'. So, make sure you use `Median()` when you are working with an ordinal variable.\n\nWe also need to assure that NAs are not included for the calculation. As we have seen a few times, R will not know what to do with these if we don't tell it to exclude them.\n\n::: {.cell}\n\n```{.r .cell-code}\nMedian(our_gss$happy, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] pretty happy\nLevels: not too happy < pretty happy < very happy\n```\n\n\n:::\n:::\n\nPerfect! Looks like our median is 'pretty happy'. \n\nAnd now we have all we need to report a univariate analysis of a categorical variable in this course:\n\n- A frequency table\n- A bar plot\n- A median or mode\n\nFor now, it's just important that you can accurately identify the median or mode of a categorical value. We'll talk about ways to implement it in the tables a little later on when we focus on publication-ready tables and figures.\n\nNow, let's talk about presenting a univariate analysis of numeric data.\n\n\n",
    "supporting": [
      "univariate_categorical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}