{
  "hash": "29463b9e0d3448dcd287f6fe480ac616",
  "result": {
    "engine": "knitr",
    "markdown": "# Univariate: Numeric\n\nWhile we also want to report on the frequency distribution and central tendency of numeric variables, there are some differences in the way we go about that relative to the techniques we just learned about for categorical variables.\n\nAdditionally, we will need to report on some measures of dispersion that can only be reported for numeric data, such as the standard deviation.\n\nThis section will walk us through the process of calculating and reporting necessary elements of a univariate analysis of numeric data.\n\n## Frequency Distributions\n\nAs we saw when we were recoding `age` earlier in the unit, a frequency table is not really appropriate for numeric data. When there are upwards of 71 different response values---as we have with `age`---a table would be both spatially unwieldy and difficult to interpret.\n\nSo, let's start with a style of plotting data that is essentially the barplot of numeric data.\n\nFirst, let's go ahead and set up our environment by loading in our data and `tidyverse` per usual.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nload(\"our_gss.rda\")\n```\n:::\n\n\n::: {.cell}\n\n:::\n\n\n\n### Histograms\n\nA histogram is the result of taking a numeric variable, slicing it up into equal, ordinal intervals, and then plotting the frequency of each interval.\n\nThere are plenty of other ways for plotting numeric data---some of which we will see later when we focus on visualization---but for now, this is a simple and effective way to get a sense of the distribution of a numeric variable. This is especially important when we need to decide on an appropriate measure of central tendency.\n\nWe can create these easily using the `hist()` function, which is in the same family of base R plotting functions as `barplot()`, so much of what we learned for that function will also apply with `hist()`. This function will automatically apply a commonly used method called Sturges's rule to divide our numeric variable into equal bins, so we do not have to specify anything in that regard.\n\nAll we need to do is give the `hist()` function our numeric variable. Let's work with the `realrinc` variable for this example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(our_gss$realrinc)\n```\n\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nMuch like we did with `barplot()`, we can clean this up a little by adding a title and a better label for the x axis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(\n  our_gss$realrinc,\n  main = \"Income distribution of GSS Respondents\",\n  xlab = \"Respondent's income in dollars\",\n  )\n```\n\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nNow we have our histogram!\n\nHowever, this visualization does suggest that we need to do some thinking about the appropriate measure of central tendency for `realrinc`.\n\n## Central Tendency\n\nFor numeric data, any of the 3 common measures of central tendency can be reported. However, the preferred measure for a given variable depends on its distribution.\n\nThe mean is the gold standard for numeric data, because it takes into account every single data point in its calculation, and is thus the most comprehensive index of central tendency.\n\nHowever, the mean can be misleading in some cases. The distribution should be (basically) normal in order for you to report the mean, and you will want to report the median in most other cases.\n\nI will first cover the choice of mean or median by revisiting some basics of distributions, and then I will address the rare circumstance where the mode is appropriate.\n\n### Mean or Median?\n\nIn most cases, we will be making a decision between the mean and the median. When the distribution is normal, you should report the mean---otherwise, report the median. We'll see one exception to this later, but that's generally our task.\n\nWe saw some typical distributions in our last section on uivariate analysis of categorical data. We'll return to some discussion of those basic distribution types but add a little more context for numeric data that will help us see the impact of making the wrong decision.\n\nI'm going to display a normal distribution, but this time, I'll draw a vertical line indicating the location of the mean and median.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nIn this case, we can't even really tell the mean and median apart. In fact, in a completely normal distribution, all three measures of central tendency will be equal. Remember that real-world data will rarely exhibit perfect normality, but as long as it's approximately normal, we can follow convention and report the mean.\n\nNow, let's look back at `realrinc`.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nIn the case of `realrinc`, we definitely do not have much normality going on. For one, there are some apparent outlier cases. Much of our data seems to be concentrated within about \\$0 - \\$75,000, but then we have a bunch of values at roughly double the maximum of that narrower range. And even within the range where most of our responses are clustered, we have some clear right-skew.\n\nAs we can see, because the mean takes all values into account, this makes it susceptible to non-normal distributions. It gets pulled in the direction of the outlier, which, in this case, is also the direction of the skew.\n\nSo, in any case where your numeric variable contains clear outliers and/or exhibits notable skew in either direction, you should report the median rather than the mean.\n\n### The Mode\n\nBy and large, the mode is more appropriate for categorical data. But there are some circumstances where it makes sense to report the mode for numeric data.\n\nLet's take a look at the original `age` variable to see an example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(\n  our_gss$age,\n  main = \"Age distribution of 2022 GSS Respondents\",\n  xlab = \"Respondent age in years\"\n)\n```\n\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThis isn't quite a normal distribution, but it's not exactly skewed in either direction either. And there are no apparent outliers.\n\nWhat we have here is a **bimodal** distribution.\n\nThis is what happens when we have multiple peaks in a distribution---two, in this case. We have seen several different distributions so far, but they all had only one peak in the distribution. They were differentiated on the basis of that single peak's location in the distribution. In the case of a multimodal distribution, we want to report on any notable peak.\n\nThis may be a peculiarity of the 2022 survey wave, because we wouldn't necessarily expect this, but it looks like there are two distinct central tendencies for `age`. In this case, we want to capture the two distinct peaks, meaning we need to calculate two modes.\n\nThankfully, there's a convenient function for this, but we need to install a new package, so let's install and load in `multimode`.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"multimode\")\nlibrary(multimode)\n```\n:::\n\n\nThen, we just need to provide a few arguments to the `locmodes()` function.\n\nFirst, we give the variable for which we want to calculate multiple modes.\n\nThen we give an input for `mod0`, which asks us how many modes the function should be looking for. This should be based on visual inspection of the data. We have two peaks in our distribution, so we will enter '2' for this input.\n\nLastly, we will set `display` to 'TRUE', which will show us a plot of the estimated modes superimposed onto the frequency distribution of the variable. This will let us evaluate whether the modes estimated by the function are plausible. They should match up with the visible peaks in the frequency distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocmodes(\n  our_gss$age,\n  mod0 = 2,\n  display = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEstimated location\nModes:  32.4301  66.25356 \nAntimode: 50.89506 \n\nEstimated value of the density\nModes: 0.01938966  0.01730832 \nAntimode: 0.01444287 \n\nCritical bandwidth: 2.543659\n```\n\n\n:::\n:::\n\n\nWe only really need to pay attention to the modes that it gives us (32.43 and 66.25), but it looks like this function spotted these values pretty effectively.\n\nFor a bimodal distribution like this, we can report both modes for the measure of central tendency. I don't expect we will run into too much of this, but go ahead and deal with it like this in the event that you do.\n\n## Dispersion\n\nNow, let's talk about dispersion. This is the last major element of a univariate analysis of numeric data. Actually calculating this information is quite simple in R, so we will practice with some of our GSS variables and then talk about putting all of this information together.\n\n### Range\n\nThis is perhaps the simplest measure of dispersion and comprises the minimum and maximum values of the distribution.\n\nR has a built in range function, so we can simply provide one of our variables as the input. We'll work with `realrinc` again. As we have done before, we will also need to provide `na.rm = TRUE`, as this variable column includes NAs and will confuse R otherwise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(our_gss$realrinc, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]    204.5 141848.3\n```\n\n\n:::\n:::\n\n\nAt this point, I'll also offer a reminder about the `summary()` function, which we can use to see a variety of information about the dispersion (in an addition to the central tendency).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(our_gss$realrinc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n   204.5   8691.2  18405.0  27835.3  33742.5 141848.3     1554 \n```\n\n\n:::\n:::\n\n\nFor a numeric variable, `summary()` will show us the minimum & maximum, as well as the mean & median, and the 1st & 3rd quartiles.\n\nWe can actually think of most of these elements in terms of percentiles.\n\n-   The minimum value is the 0th percentile of the distribution\n\n-   The 1st quartile is the 25th percentile.\n\n-   The median is the 50th percentile\n\n-   The 3rd quartile is the 75th percentile\n\n-   And the maximum is the 100th percentile.\n\n`summary()` is great for quickly assessing some of these descriptive statistics, but it's a little less convenient for exporting this information into something like a table for our own univariate analysis.\n\nSo, I'll also highlight the `min()` and `max()` functions, which will come in hand for us shortly. They work simply enough---we just need to provide our variable column, and they will output the minimum and maximum, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(our_gss$realrinc, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 204.5\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(our_gss$realrinc, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 141848.3\n```\n\n\n:::\n:::\n\n\n### Standard Deviation\n\nThis is one of the more commonly reported dispersion metrics for numeric data. The standard deviation is a measure of how much the average value varies from the mean. In plainer terms, it's a measure that tells us how spread out the distribution is.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](univariate_numeric_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nWe can grab the standard deviation quite easily with the `sd()` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(our_gss$realrinc, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 31962.34\n```\n\n\n:::\n:::\n\n\nNow, let's talk about putting all this together in our reporting of a univariate analysis for numeric data.\n\n## Putting It All Together\n\nNow that we have worked through how to calculate all of these key statistics with R, let's revisit some of the first `tidyverse` functions we learned about back on the first day.\n\nWe can use a combination of `select()` and `summarize` to quickly compile several bits of important information, such as the range, the central tendency, and the standard deviation.\n\nLet's do this for `realrinc`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nour_gss |>\n  select(realrinc) |>\n  summarize(\n    \"Minimum\" = min(realrinc, na.rm = TRUE),\n    \"Median\" = median(realrinc, na.rm = TRUE),\n    \"Maximum\" = max(realrinc, na.rm = TRUE),\n    \"SD\" = sd(realrinc, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Minimum Median  Maximum       SD\n1   204.5  18405 141848.3 31962.34\n```\n\n\n:::\n:::\n\n\n::: callout-note\nYou might notice that there's an attribute for each column that looks like `<dbl>`. This is short for 'double', which is itself shorthand for 'double-precision floating-point format'. This is in reference to the underlying data type that R uses to store continuous numeric values. You really don't need to know anything more about double-precision floating point than that for our purposes, but I mention it here because you might run into <dbl> or 'double' in R. When you do, just think 'numeric data'.\n:::\n\nIf you have a numeric variable where the mean is more appropriate, you can just swap `median()` with `mean()` in the code template above. Be sure to also change the column name as well.\n\nAnd that should do us! For any univariate analysis you report in this course, you will just need to produce\n\n-   a histogram displaying the variable's frequency distribution\n-   a table like the one above (with the appropriate measure of central tendency).\n",
    "supporting": [
      "univariate_numeric_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}